# Generated by Django 5.0.3 on 2024-08-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenFoodMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('menu', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('calorie', models.IntegerField()),
                ('item_photo', models.ImageField(null=True, upload_to='item_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='CanteenFoodRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caterer_name', models.CharField(max_length=50)),
                ('cateen_item_name', models.CharField(max_length=50)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('employer_contribution', models.FloatField()),
                ('employee_contribution', models.FloatField()),
                ('caterer_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Caterer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caterer_name', models.CharField(max_length=50)),
                ('cateen_item_name', models.CharField(max_length=50)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
            ],
        ),
    ]
