# Generated by Django 5.0.3 on 2024-08-03 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_canteenfoodmenu_canteenfoodrate_caterer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caterer',
            old_name='cateen_item_name',
            new_name='canteen_item_name',
        ),
    ]
