# Generated by Django 5.0.3 on 2024-08-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_cateen_item_name_caterer_canteen_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canteenfoodrate',
            old_name='cateen_item_name',
            new_name='canteen_item_name',
        ),
    ]
