# Generated by Django 5.0.3 on 2024-08-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_canteenfoodrate_employee_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteenfoodmenu',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
    ]
