# Generated by Django 5.0.3 on 2024-08-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_caterermenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caterermenu',
            name='food_menu',
        ),
        migrations.AddField(
            model_name='caterermenu',
            name='food_menu',
            field=models.ManyToManyField(to='users.canteenfoodmenu'),
        ),
    ]
