# Generated by Django 5.0.3 on 2024-08-26 06:41

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_circular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circular',
            name='media',
            field=models.FileField(upload_to='circularmedia/', validators=[users.models.validate_file_type]),
        ),
        migrations.CreateModel(
            name='CircularMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField()),
                ('circulars', models.ManyToManyField(related_name='circular_menus', to='users.circular')),
            ],
        ),
    ]
