# Generated by Django 5.0.3 on 2024-08-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_circular_media_circularmenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circularmenu',
            name='circulars',
        ),
        migrations.AddField(
            model_name='circularmenu',
            name='circular',
            field=models.ManyToManyField(to='users.circular'),
        ),
    ]
